### ISSUE TITLE
CRHM GUI will not launch on windows

### ISSUE THREAD

**Issue by tmahmood469** [srlabUsask/crhmcode#418]
When I click the CRHM GUI.. no GUI pops up.. 
However, I am able to run CRHM_GUI from the command prompt by typing CRHM_GUI  example.prj
Am I missing anything while installing?

**Comment by jhs507** [comment]
There is a known issue where the location of the executable needs to be in a directory where the local user has full permissions. 

There is a workaround. If you copy the whole folder containing the CRHM_GUI.exe and all of the supplemental files to your windows home directory and try to run it from there I have found that that works.

**Comment by tmahmood469** [comment]
Thank you. When I try to run as an admin from C drive, it says "No Output
selected"
I copied the entire chrm_code folder to "Desktop" and also to "Documents".
Then I clicked CRHM_GUI but nothing pop up.
Is there anything I can do to fix this?

Taufique

**Comment by tmahmood469** [comment]
Unfortunately, it is not working.
I also could not compile the latest version of the CRHM based on the
provided instructions in Ubuntu.

**Comment by jhs507** [comment]
Could you detail your process for downloading and installing CRHM_GUI on your windows machine? I will do my best to recreate your process and see if I can advise you. 

As far as compiling and running on Ubuntu could you open a separate issue and detail your process for that there. I will see if I can figure out why compilation is not working for you.

**Comment by lawfordp2017** [comment]
Hi Justin,
I have this same problem when downloading version 1.3.1 from github releases, installing and running using wine on Linux. Also, I have one question as a non-windows programmer, how does the gui start up without a WinMain routine?

**Comment by jhs507** [comment]
For me I use the .msi installer and install at the default location "C:\Program Files (x86)\CRHMcode". 
Then I copy the CRHM_GUI directory to a location where I have full permissions such as the desktop.
Then running the CRHM_GUI.exe correctly opens the GUI.

As far as how it starts without a WinMain routine that is handled by the MFC library. 
This article explains how it works under the hood. https://www.codeproject.com/Articles/1672/MFC-under-the-hood

**Comment by tmahmood469** [comment]
Justin,

This is exactly what I did on two windows machines. Install using the msi
file and then copy the entire chrm_code folder to Documents and Desktop..
Then, I click the CRHM_GUI, it rotates twice around the cursor and then
nothing shows up (trying as an admin too)... I am looking for a GUI for
high school outreach (Native American Reservation) as a part of a cold
region hydrology workshop next spring...

**Comment by jhs507** [comment]
Humm that process works for me. 

Can you:

1.  Delete any .log file in the CRHM_GUI folder
2. Attempt to run CRHM_GUI.exe 
3. Upload the .log file if it is generated

This might help me see what is going on. It is hard to diagnose the issue.

**Comment by lawfordp2017** [comment]
Justin,
In your InitInstance routine it might be a good idea to use a string equality check instead of:
if (args->get_project_name() != "")
those two things will likely never be equal since you're comparing pointers. So it will always try to run the 'model' even if non-existant and it will fail.
At least I think that's what's happening. Haven't got VS2019 installed so can't compile myself.

**Comment by jhs507** [comment]
Based on what I have seen so far that would make sense. I will alter that and see if it fixes things. Thank you Peter.

**Comment by jhs507** [comment]
I have fixed the equality check that Peter has pointed out but I am unsure if it has fixed this issue. It was something that needed to be fixed anyway.

**Comment by jhs507** [comment]
I have shared the executable with you on One Drive

**Comment by lawfordp2017** [comment]
Justin,
Thanks for the updated executable, sorry for the confusion the other day.
The change I suggested seems to not have fixed the problem, but I do have another suggestion. When CRHMCODE is run from console or from visual studio the first 'GetCommandLine' argument is the name of the executable 'crhmcode_ui'. When CRHMCODE is run by clicking on the icon the first argument is the full path to the executable 'c:\program files (x86)\... '. Since this path has spaces it gets tokenized into multiple arguments and assigns part of the path to get_project_name, which is invalid. I think it may be better to use a specialized tokenizer like CommandLineToArgvW if possible.

**Comment by jhs507** [comment]
I have been able to recreate this error by placing a space in the path of the location of the executable. 

This also explains why it will not launch correctly when it is placed in the "Program Files (x86)" directory. I thought this was a permissions issue but it is because of the spaces in the path. 

I had just by coincidence only been attempting to run it from locations with a path that did not contain any spaces. 

This explains the behavior reported quite well as because of the way the path is parsed as an argument it attempts to run in command line mode and crashes when it can't find the project file the "argument" is pointing to. 

Thanks for this catch Peter.

**Comment by BZ840** [comment]
Hi @jhs507 
My colleague and I are having trouble opening the GUI. We downloaded the .msi from [here](https://github.com/srlabUsask/crhmcode/releases/tag/Release_v1.3.1), and initially installed it to the default path. Nothing popped up when we opened the CRHM_GUI.exe. Then we uninstall and reinstall it to the Desktop and D drive separately, still didn't work. We made sure there's no space in the path of the installation location, and even tried to run as admin.
Any suggestions?

**Comment by jhs507** [comment]
@BZ840 When you attempt to run CRHM_GUI.exe is a .log file produced? If it is can you post it so I can examine it. 

If it isn't the issue of there being a space in the full path to the executable I can't think of anything off the top of my head.

**Comment by BZ840** [comment]
@jhs507 there's no .log file produced.

**Comment by BZ840** [comment]
@jhs507 yes, there's no error msg at all, and nothing related to CRHM_GUI running (at least I checked the task manager)

My colleague did have a log file, and here is the content:
[2022-11-16 16:10:12.543] [run_log] [info] [CRHMLogger.cpp:93] cannot open file, File Error
[2022-11-16 16:10:18.669] [run_log] [info] [CRHMLogger.cpp:93] End of model run: 44881.7 2022 11 16. Program Version: 4.7_16

**Comment by jhs507** [comment]
@BZ840 

The log file your colleague experienced is what I get when I try to run it when there is a space in the full path to the executable. I haven't had time to fix this known issue yet. 

 The lack of any error message or log file stumps me a bit. I will have to think on this.

**Comment by BZ840** [comment]
@jhs507 Not sure if it is relevant, I do have the previous version of CRHM installed, but this is the very first time I installed CRHM_GUI.

**Comment by jhs507** [comment]
@BZ840 

I can't imagine that will have any effect. They are completely independent systems.
